apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: puppet-code-claim
  labels:
    {{- include "puppetserver.puppetserver.labels" . | nindent 4 }}
  {{- if .Values.storage.annotations }}
  annotations:
    {{ toYaml .Values.storage.annotations | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.code.size | quote }}
  {{- if .Values.storage.storageClass }}
  {{- if (eq "-" .Values.storage.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.storage.storageClass }}"
  {{- end }}
  {{- end }}
